function local_parallel_dashboard_bugfixed(varargin)
%LOCAL_PARALLEL_DASHBOARD_BUGFIXED Convenience wrapper for bugfixed settings.
%
% Enables bugfixed BAUCB bookkeeping (fixed joint-state visit counts) and
% otherwise stays close to the legacy dashboard settings.
%
% Example:
%   local_parallel_dashboard_bugfixed('Seed', 1, 'NumTrials', 20)

    algorithms = { ...
        'SI', 'SI_novelty', 'SI_novelty_smooth', ...
        'SL_noSmooth', 'SL', ...
        'BA', 'BAUCB' ...
    };

    weights = struct(...
        'novelty', 10, ...
        'learning', 40, ...
        'epistemic', 1, ...
        'preference', 10, ...
        'ucb_scale', 5, ...
        'state_selection', 'sample', ...
        'preference_param', 'weight', ...
        'baucb_variant', 'fixed_joint_counts', ...
        'real_smoothing', true, ...
        'adaptive_likelihood_in_plan', false, ...
        'learning_prune_threshold', 0.2 ...
    );

    local_parallel_dashboard( ...
        'Algorithms', algorithms, ...
        'Weights', weights, ...
        'DashboardTitle', 'Local Parallel Dashboard — Bugfixed', ...
        varargin{:} ...
    );
end

