function local_parallel_dashboard_bugfixed_adaptivePlan(varargin)
%LOCAL_PARALLEL_DASHBOARD_BUGFIXED_ADAPTIVEPLAN Bugfixed + adaptive planning dashboard.
%
% Same as local_parallel_dashboard_bugfixed, but enables the opt-in
% "adaptive_likelihood_in_plan" (TODO) switch so SL's counterfactual
% parameter updates also update the branch-local likelihood y{2}.
%
% Example:
%   local_parallel_dashboard_bugfixed_adaptivePlan('Seed', 1, 'NumTrials', 20)

    algorithms = { ...
        'SI', 'SI_novelty', 'SI_novelty_smooth', ...
        'SL_noSmooth', 'SL', ...
        'BA', 'BAUCB' ...
    };

    weights = struct(...
        'novelty', 10, ...
        'learning', 40, ...
        'epistemic', 1, ...
        'preference', 10, ...
        'ucb_scale', 5, ...
        'state_selection', 'sample', ...
        'preference_param', 'weight', ...
        'baucb_variant', 'fixed_joint_counts', ...
        'real_smoothing', true, ...
        'adaptive_likelihood_in_plan', true, ...
        'learning_prune_threshold', 0.2 ...
    );

    local_parallel_dashboard( ...
        'Algorithms', algorithms, ...
        'Weights', weights, ...
        'DashboardTitle', 'Local Parallel Dashboard — Bugfixed + AdaptivePlan', ...
        varargin{:} ...
    );
end

