function local_parallel_dashboard_legacy(varargin)
%LOCAL_PARALLEL_DASHBOARD_LEGACY Convenience wrapper for paper/legacy settings.
%
% Runs a non-redundant set of algorithms under legacy-compatible switches.
%
% Example:
%   local_parallel_dashboard_legacy('Seed', 1, 'NumTrials', 20)

    algorithms = { ...
        'SI', 'SI_novelty', 'SI_novelty_smooth', ...
        'SL_noSmooth', 'SL', ...
        'BA', 'BAUCB' ...
    };

    weights = struct(...
        'novelty', 10, ...
        'learning', 40, ...
        'epistemic', 1, ...
        'preference', 10, ...
        'ucb_scale', 5, ...
        'state_selection', 'sample', ...
        'preference_param', 'weight', ...
        'baucb_variant', 'legacy', ...
        'real_smoothing', true, ...
        'adaptive_likelihood_in_plan', false, ...
        'learning_prune_threshold', 0.2 ...
    );

    local_parallel_dashboard( ...
        'Algorithms', algorithms, ...
        'Weights', weights, ...
        'DashboardTitle', 'Local Parallel Dashboard — Legacy', ...
        varargin{:} ...
    );
end

