function local_parallel_dashboard_bugfixed_compareAdaptivePlan(varargin)
%LOCAL_PARALLEL_DASHBOARD_BUGFIXED_COMPAREADAPTIVEPLAN Compare SL adaptive planning variants.
%
% Runs SI variants plus SL variants with and without the opt-in
% "adaptive_likelihood_in_plan" switch, using paired seeds.
%
% Example:
%   local_parallel_dashboard_bugfixed_compareAdaptivePlan('Seeds', 1:5, 'NumTrials', 50)

    algorithms = { ...
        'SI', 'SI_novelty', 'SI_novelty_smooth', ...
        'SL_noSmooth', 'SL', ...
        'SL_noSmooth_adaptivePlan', 'SL_adaptivePlan' ...
    };

    weights = struct(...
        'novelty', 10, ...
        'learning', 40, ...
        'epistemic', 1, ...
        'preference', 10, ...
        'ucb_scale', 5, ...
        'state_selection', 'sample', ...
        'preference_param', 'weight', ...
        'baucb_variant', 'fixed_joint_counts', ...
        'real_smoothing', true, ...
        'adaptive_likelihood_in_plan', false, ...
        'learning_prune_threshold', 0.2 ...
    );

    local_parallel_dashboard( ...
        'Algorithms', algorithms, ...
        'Weights', weights, ...
        'DashboardTitle', 'Local Parallel Dashboard - Bugfixed (Compare AdaptivePlan)', ...
        varargin{:} ...
    );
end
